name: PluginControl
main: com.woxloi.plugincontrol.PluginControl
version: 1.0
api-version: 1.20

commands:
  plugincontrol:
    permission: plugincontrol.admin
    aliases:
      - pcontrol
permissions:
  plugincontrol.admin:
    default: op